import type { Direction, OutcomeTier } from '../../shared/types/game'

export const UI_COPY = {
  board: {
    eyebrow: 'Board',
    heading: 'Find the richest legal route',
    keyboardHint: 'Click tiles or use arrow keys',
  },
  sidebar: {
    eyebrow: 'Daily Challenge',
    heroCopy: 'The goal is not to collect everything. The goal is to discover the best legal route.',
    reloadToday: 'Reload Today',
    legend: 'Legend',
    hints: 'Hints',
    metrics: {
      score: 'Score',
      boardCoins: 'Board Coins',
      moves: 'Moves',
      progress: 'Progress',
    },
    runStatusEyebrow: 'Run Status',
    routeActive: 'Route Active',
    routeComplete: 'Route Complete',
    defaultHintInline: 'Use hints only when you need help. They stay tucked away until you ask for them.',
    openHints: 'Open Hints',
    openLegend: 'Open Legend',
    overlayHelpEyebrow: 'Help',
    close: 'Close',
    hintsTitle: 'Hints',
    legendTitle: 'Legend',
    hintRows: {
      level1Title: 'Nudge',
      level1Desc: 'Highlights the next best move',
      level2Title: 'Path Preview',
      level2Desc: 'Shows the next few best tiles',
      level3Title: 'Rescue',
      level3Desc: 'Reveals the exact next best tile',
    },
    hintFallback: 'Hints appear here after you request one.',
    legendRows: {
      legalMove: 'Legal next move',
      visitedTile: 'Visited tile',
      blockedRoad: 'Blocked road',
      costRoad: 'Cost road',
      bonusRoad: 'Bonus road',
      start: 'Start',
      end: 'End',
    },
  },
  completion: {
    eyebrow: 'Run Complete',
    headingFallback: 'Road complete',
    labels: {
      finalScore: 'Final score',
      goldTarget: 'Gold target',
      moves: 'Moves',
      outcome: 'Outcome',
      playAnother: 'Play Another',
      reloadToday: 'Reload Today',
    },
    tiers: {
      gold: 'Perfect route',
      silver: 'Excellent route',
      bronze: 'Strong route',
      finished: 'Finished route',
      unfinished: 'Unfinished route',
    } as Record<OutcomeTier, string>,
  },
  runtime: {
    loadingGame: 'Loading game...',
    loadingTodaysRoad: 'Loading today\'s road...',
    findingAnotherRoad: 'Finding another road...',
    introStatus: 'Find the richest legal path to the exit. Dark bars are blocked roads.',
    destinationReached: 'Destination reached.',
    deadEnd: 'Dead end reached. This route cannot continue.',
    hint1Highlighted: 'Hint: the next best move is highlighted on the board.',
    hint1Direction: (direction: Direction) => `Hint: move ${direction}.`,
    hint2Suggested: (tileIndexes: number[]) => `Hint: suggested route nodes ${tileIndexes.join(', ')}.`,
    hint3Next: (nextTileIndex: number) => `Hint: next best tile is ${nextTileIndex}.`,
  },
} as const
